"""empty message

Revision ID: a4d7a4a91260
Revises: d8712cc8fe0e
Create Date: 2018-04-09 09:01:54.980932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4d7a4a91260'
down_revision = 'd8712cc8fe0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('author', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('comment', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('post', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'create_time')
    op.drop_column('post', 'updated_at')
    op.alter_column('comment', 'create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('comment', 'updated_at')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'create_time')
    op.drop_column('author', 'updated_at')
    op.drop_column('author', 'create_time')
    # ### end Alembic commands ###
