"""empty message

Revision ID: d8712cc8fe0e
Revises: dbc42435f8e0
Create Date: 2018-04-03 13:43:33.059824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8712cc8fe0e'
down_revision = 'dbc42435f8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('author', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('author', sa.Column('role', sa.SmallInteger(), nullable=True))
    op.add_column('author', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_author_username'), 'author', ['username'], unique=True)
    op.create_unique_constraint(None, 'author', ['email'])
    op.drop_column('author', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_index(op.f('ix_author_username'), table_name='author')
    op.drop_column('author', 'username')
    op.drop_column('author', 'role')
    op.drop_column('author', 'password')
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
